// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU5ydpTB7CIz6QE_RTlwXof21PatsHJWs',
    appId: '1:962907525361:web:c299498221a6438a989950',
    messagingSenderId: '962907525361',
    projectId: 'final-mobile-project-b7f32',
    authDomain: 'final-mobile-project-b7f32.firebaseapp.com',
    storageBucket: 'final-mobile-project-b7f32.firebasestorage.app',
    measurementId: 'G-FKRC9FHRVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA51zsbcSOhVbJ5ppFyfqDmSKfADWozcy0',
    appId: '1:962907525361:android:315f71867f41f208989950',
    messagingSenderId: '962907525361',
    projectId: 'final-mobile-project-b7f32',
    storageBucket: 'final-mobile-project-b7f32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkV9jqEfZEP3YFY70abxHZZC6Hj3fKFK0',
    appId: '1:962907525361:ios:3a8532391db8f5aa989950',
    messagingSenderId: '962907525361',
    projectId: 'final-mobile-project-b7f32',
    storageBucket: 'final-mobile-project-b7f32.firebasestorage.app',
    iosBundleId: 'com.example.finalMobileProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkV9jqEfZEP3YFY70abxHZZC6Hj3fKFK0',
    appId: '1:962907525361:ios:3a8532391db8f5aa989950',
    messagingSenderId: '962907525361',
    projectId: 'final-mobile-project-b7f32',
    storageBucket: 'final-mobile-project-b7f32.firebasestorage.app',
    iosBundleId: 'com.example.finalMobileProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU5ydpTB7CIz6QE_RTlwXof21PatsHJWs',
    appId: '1:962907525361:web:7ed9879a5526a77b989950',
    messagingSenderId: '962907525361',
    projectId: 'final-mobile-project-b7f32',
    authDomain: 'final-mobile-project-b7f32.firebaseapp.com',
    storageBucket: 'final-mobile-project-b7f32.firebasestorage.app',
    measurementId: 'G-ZX5M35Z4NF',
  );
}
